from django.urls import path

from .views import (
    AreaDetailView,
    AreaListCreateView,
    ClientDetailView,
    ClientListCreateView,
    ClientFeedbackView,
    ClaimDetailView,
    ClaimListCreateView,
    ClaimActionView,
    ClaimCommentView,
    ClaimTimelineView,
    EmployeeDetailView,
    EmployeeListCreateView,
    LoginView,
    ProjectDetailView,
    ProjectListCreateView,
    SubAreaView,
    StatisticsView,
    StatisticsByMonthView,
    StatisticsByStatusView,
    StatisticsByTypeView,
    StatisticsByAreaView,
    StatisticsByProjectView,
    StatisticsAverageResolutionTimeView,
    StatisticsKPIsView,
    StatisticsRatingsView,
    StatisticsByEmployeeView,
)

urlpatterns = [
    path("auth/login/", LoginView.as_view(), name="login"),
    path("areas/", AreaListCreateView.as_view(), name="area-list"),
    path("areas/<str:area_id>/", AreaDetailView.as_view(), name="area-detail"),
    path("areas/<str:area_id>/sub-areas/", SubAreaView.as_view(), name="sub-area-create"),
    path("areas/<str:area_id>/sub-areas/<str:sub_area_id>/", SubAreaView.as_view(), name="sub-area-detail"),
    path("employees/", EmployeeListCreateView.as_view(), name="employee-list"),
    path("employees/<str:user_id>/", EmployeeDetailView.as_view(), name="employee-detail"),
    path("clients/", ClientListCreateView.as_view(), name="client-list"),
    path("clients/<str:user_id>/", ClientDetailView.as_view(), name="client-detail"),
    path("projects/", ProjectListCreateView.as_view(), name="project-list"),
    path("projects/<str:project_id>/", ProjectDetailView.as_view(), name="project-detail"),
    path("claims/", ClaimListCreateView.as_view(), name="claim-list"),
    path("claims/<str:claim_id>/", ClaimDetailView.as_view(), name="claim-detail"),
    path("claims/<str:claim_id>/actions/", ClaimActionView.as_view(), name="claim-action"),
    path("claims/<str:claim_id>/comments/", ClaimCommentView.as_view(), name="claim-comment"),
    path("claims/<str:claim_id>/feedback/", ClientFeedbackView.as_view(), name="client-feedback"),
    path("claims/<str:claim_id>/timeline/", ClaimTimelineView.as_view(), name="claim-timeline"),
    path("statistics/", StatisticsView.as_view(), name="statistics"),
    path("statistics/by-month/", StatisticsByMonthView.as_view(), name="statistics-by-month"),
    path("statistics/by-status/", StatisticsByStatusView.as_view(), name="statistics-by-status"),
    path("statistics/by-type/", StatisticsByTypeView.as_view(), name="statistics-by-type"),
    path("statistics/by-area/", StatisticsByAreaView.as_view(), name="statistics-by-area"),
    path("statistics/by-project/", StatisticsByProjectView.as_view(), name="statistics-by-project"),
    path("statistics/avg-resolution-time/", StatisticsAverageResolutionTimeView.as_view(), name="statistics-avg-time"),
    path("statistics/kpis/", StatisticsKPIsView.as_view(), name="statistics-kpis"),
    path("statistics/ratings/", StatisticsRatingsView.as_view(), name="statistics-ratings"),
    path("statistics/by-employee/", StatisticsByEmployeeView.as_view(), name="statistics-by-employee"),
]
